export default function TermsPage() {
  return (
    <div className="flex-1 py-12">
      <div className="landing-container max-w-3xl">
        <h1 className="text-4xl font-semibold m-0">Terms of Service</h1>
        <p className="text-sm text-[color:var(--color-muted-foreground)] mt-1">Last updated: today</p>

        <Section title="Acceptance">
          <p>
            By creating an account or using LegalScan, you agree to these Terms. If you do not agree,
            please do not use the service.
          </p>
        </Section>

        <Section title="Nature of the service">
          <p>
            LegalScan is an educational software tool. We provide informational scans of consumer credit
            report data and generate template dispute letters citing relevant portions of the Fair
            Credit Reporting Act and related consumer protection statutes. We are not a credit repair
            organization, a law firm, or a financial advisor, and we do not provide legal advice.
          </p>
        </Section>

        <Section title="No guarantees">
          <p>
            No outcome — including any specific change to your credit score, the removal of items from
            your credit file, or the response of any credit reporting agency or furnisher — is
            guaranteed. Results depend on the accuracy of the information you provide and the
            independent investigation conducted by third parties.
          </p>
        </Section>

        <Section title="Your responsibilities">
          <p>
            You agree to provide accurate information and to use the dispute letters generated by the
            service only for legitimate disputes you believe in good faith are appropriate under the
            FCRA. Submitting knowingly false statements to a credit reporting agency may be a violation
            of federal law.
          </p>
        </Section>

        <Section title="Payments & refunds">
          <p>
            Payments for one-time scans and lifetime access are processed through Stripe. If a scan
            returns zero flagged items, contact support within 14 days for a full refund.
          </p>
        </Section>

        <Section title="Termination">
          <p>
            You may delete your account at any time. We may suspend or terminate access for users who
            violate these Terms.
          </p>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="text-xl font-semibold m-0">{title}</h2>
      <div className="mt-2 text-[15px] text-[color:var(--color-foreground)] leading-relaxed [&_p]:m-0 [&_p+p]:mt-3">
        {children}
      </div>
    </section>
  );
}
